apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: production
  labels:
    app: 13-02-frontend
spec:
  selector:
    matchLabels:
      app: 13-02-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: 13-02-frontend
    spec:
      initContainers:
        - name: wait-backend
          image: praqma/network-multitool:alpine-extra
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-ec"]
          args: ['while [ $(curl -ksw "%{http_code}" "backend-cip:9000/api/news/" -o /dev/null) -ne 200 ]; do sleep 5; echo "Waiting for backend service."; done']
      containers:
        - image: rpot/13-01-frontend:0.1
          imagePullPolicy: IfNotPresent
          name: frontend
          env:
            - name: BASE_URL
              value: http://backend-cip:9000
          volumeMounts:
            - mountPath: "/static"
              name: my-volume
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: pvc-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: production
  labels:
    app: 13-02-frontend
spec:
  selector:
    app: 13-02-frontend
  type: LoadBalancer
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
