{{- $release := .Release.Name }}
{{- $backendname := .Values.backend.service.name }}
{{- $imagePullPolicy := .Values.global.imagePullPolicy }}
{{- with .Values.frontend }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $release }}-{{ .app }}
  labels:
    app: {{ .app }}
spec:
  selector:
    matchLabels:
      app: {{ .app }}
  replicas: {{ .replicas }}
  template:
    metadata:
      labels:
        app: {{ .app }}
    spec:
      initContainers:
      - name: wait-backend
        image: praqma/network-multitool:alpine-extra
        imagePullPolicy: {{ $imagePullPolicy }}
        command: ["/bin/sh","-ec"]
        args: ['while [ $(curl -ksw "%{http_code}" "{{ $release }}-{{ $backendname }}:9000/api/news/" -o /dev/null) -ne 200 ]; do sleep 5; echo "Waiting for backend service."; done']
      containers:
      - image: rpot/13-01-frontend:{{ .version }}
        imagePullPolicy: {{ $imagePullPolicy }}
        name: frontend
        env:
        {{- range $key, $val := .env }}
        - name: {{ $val.name }}
        {{- if contains "<ServicePort>" $val.value }}
          value: {{ $val.value | replace "<ServicePort>" (print $release "-" $backendname) }}
        {{- else }}
          value: {{ $val.value }}
        {{- end }}
        {{- end }}
{{ end }}
