{
 "title": "Netology_10-03",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by(instance)(rate(node_cpu_seconds_total{instance=\"node-exporter:9100\", mode=\"idle\"}[$__interval])) * 100",
     "legendFormat": "{{mountpoint}} - idle"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load1{instance=\"node-exporter:9100\"}[$__rate_interval]))",
     "legendFormat": "{{mountpoint}} - load1"
    },
    {
     "expr": "avg by (instance)(rate(node_load5{instance=\"node-exporter:9100\"}[$__rate_interval]))",
     "legendFormat": "{{mountpoint}} - load5"
    },
    {
     "expr": "avg by (instance)(rate(node_load15{instance=\"node-exporter:9100\"}[$__rate_interval]))",
     "legendFormat": "{{mountpoint}} - load15"
    }
   ]
  },
  {
   "title": "Mem Free/Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "- MemFree"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "- MemAvailable"
    }
   ]
  },
  {
   "title": "Filesystem used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - node_filesystem_avail_bytes{fstype!='tmpfs', instance=\"node-exporter:9100\"} / node_filesystem_size_bytes * 100",
     "legendFormat": "FS used"
    }
   ]
  }
 ]
}