version: "3.8"

networks:
  net:
    driver: bridge

volumes:
    prometheus: {}
    grafana: {}

services:
  grafana:
    # https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/
    container_name: grafana
    image: grafana/grafana:7.5.10
    networks:
      - net
    environment:
      # Config anonymous login
      # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_SIGNOUT_MENU=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      # https://grafana.com/docs/grafana/latest/administration/provisioning/
      # https://grafana.com/tutorials/provision-dashboards-and-data-sources/
      # https://grafana.com/docs/grafana/latest/dashboards/json-model/
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  node-exporter:
    # Config for docker compose
    # https://grafana.com/docs/grafana-cloud/quickstart/docker-compose-linux/
    image: prom/node-exporter
    container_name: node-exporter
    networks:
      - net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  prometheus:
    # https://grafana.com/docs/grafana-cloud/quickstart/docker-compose-linux/
    # https://prometheus.io/docs/prometheus/latest/installation/#using-docker
    container_name: prometheus
    image: prom/prometheus
    networks:
      - net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=${PROMETHEUS_RETENTION:-240h}' # It defines how long data is kept in TSDB. The default is 15 days
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus:/prometheus
    expose:
      - 9090
    depends_on:
      - node-exporter
