apiVersion: v1
kind: ServiceAccount
metadata:
  name: netology

---
apiVersion: v1
kind: Pod
metadata:
  name: multitool
spec:
  containers:
  - name: multitool
    image: praqma/network-multitool:alpine-extra
    imagePullPolicy: IfNotPresent
  serviceAccount: netology
