apiVersion: v1
kind: Service
metadata:
  name: external-geocode
  namespace: default
spec:
  selector: {} 
  ports:
    - name: "external-geocode"
      protocol: "TCP"
      port: 443
---
# api.bigdatacloud.net
apiVersion: v1
kind: Endpoints
metadata:
  name: external-geocode
  namespace: default
subsets:
  - addresses:
      - ip: "13.248.207.97"
    ports:
      - name: external-geocode
        port: 443
