{
 "title": "netology_11-03",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total objects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_bucket_usage_object_total",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Status 200",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job)(http_request_duration_seconds_count{status=\"200\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "ERROR",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job)(http_request_duration_seconds_count{status!=\"200\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "MINIO",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minio_s3_requests_total", "legendFormat": "{{api}}" }
   ]
  }
 ]
}