version: '3.9'

volumes:
  data: {}

services:
  postgres:
    container_name: postgres_container
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
      - ./db:/src:rw
      