version: '3.9'

volumes:
  data: {}
  backup: {}

services:
  postgres:
    container_name: postgres_container
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
      - backup:/var/lib/postgresql/backup
      - ./db/init.pgsql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/src:ro
      