---
- name: Import remi GPG key.
  rpm_key:
    key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
    state: present

- name: Install remi repo.
  yum:
    name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present

- name: Install redis packages from remi
  ansible.builtin.yum:
    name:
      - redis
    state: latest
    update_cache: yes
    enablerepo: "remi"
