---
- name: Create redis service
  become: true
  ansible.builtin.template:
    src: redis.service.j2
    dest: /usr/lib/systemd/system/redis-{{ redis_port }}.service
    owner: root
    group: root
    mode: '0644'

- name: Create limits file
  become: true
  ansible.builtin.template:
    src: limit.conf.j2
    dest: /etc/systemd/system/redis-{{ redis_port }}.service.d/limit.conf
    owner: root
    group: root
    mode: '0644'

- name: Start redis-{{ redis_port }} service
  become: true
  ansible.builtin.service:
    name: redis-{{ redis_port }}
    state: started
    daemon_reload: true
    enabled: yes

- name: Wait for Redis Server to Become Ready
  ansible.builtin.wait_for:
    port: "{{ redis_port }}"
    delay: 5
