apiVersion: v1
kind: Service
metadata:
  name: hello-node
  labels:
    app: hello-node
    tier: frontend
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-node
  type: LoadBalancer
