apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: production
  labels:
    app: 13-01-backend
spec:
  selector:
    matchLabels:
      app: 13-01-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: 13-01-backend
    spec:
      initContainers:
      - name: wait-postgres
        image: postgres:13-alpine
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -ec
        - |
          until (pg_isready -h postgres-db-cip -p 5432 -U postgres); do
            echo 'Wait postgres service'
            sleep 1
          done
      containers:
      - image: rpot/13-01-backend:0.1
        imagePullPolicy: IfNotPresent
        name: backend
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@postgres-db-cip:5432/news
---
apiVersion: v1
kind: Service
metadata:
  name: backend-cip
  namespace: production
  labels:
    app: 13-01-backend
spec:
  selector:
    app: 13-01-backend
  type: ClusterIP
  ports:
  - name: backend
    protocol: TCP
    port: 9000
    targetPort: 9000
