apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config

data:
  config.hcl: |
    ui = true
    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
    }
    storage "file" {
      path = "/vault/data"
    }
    log_level = "debug"
  VAULT_ADDR: http://127.0.0.1:8200