---
## Container runtime
## docker for docker, crio for cri-o and containerd for containerd.
container_manager: containerd

# Choose network plugin (cilium, calico, kube-ovn, weave or flannel. Use cni for generic cni plugin)
kube_network_plugin: calico

## Supplementary addresses that can be added in kubernetes ssl keys.
## That can be useful for example to setup a keepalived virtual IP
supplementary_addresses_in_ssl_keys: [127.0.0.1, "{{ hostvars['control01']['ansible_host'] }}"]
