---
imagePullPolicy: IfNotPresent
gitlabUrl: http://51.250.88.173/
runnerRegistrationToken: "GR13489412UaMeyhtAfzC6-FBu4Fg"
terminationGracePeriodSeconds: 3600
concurrent: 10
checkInterval: 30
sessionServer:
 enabled: false
rbac:
  create: true
  clusterWideAccess: true
  podSecurityPolicy:
    enabled: false
    resourceNames:
      - gitlab-runner
runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "{{.Release.Namespace}}"
        image = "ubuntu:20.04"
        privileged = true