---
  - name: Install packages
    become: true
    ansible.builtin.apt: >
      name={{ item }}
      state=present
      update_cache=yes
    with_items:
      - conntrack
      - docker.io
      - iproute2
      - socat
