apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: demo
spec:
  environments:
    default:
      defaultNamespace: default
      server: https://178.154.241.63:6443
    stage:
      defaultNamespace: stage
      server: https://178.154.241.63:6443
    prod:
      defaultNamespace: production
      server: https://178.154.241.63:6443
      includes:
      - endpoint
  vars: {}
  excludes:
  - endpoint