version: '3.8'

volumes:
  es_hot_data: {}
  es_warm_data: {}

networks:
  elk:
    driver: bridge

services:
  es-hot:
    image: elasticsearch:7.17.2
    container_name: es-hot
    environment:
      - node.name=es-hot
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es-hot,es-warm
      - discovery.seed_hosts=es-warm
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es_hot_data:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
    networks:
      - elk

  es-warm:
    image: elasticsearch:7.17.2
    container_name: es-warm
    environment:
      - node.name=es-warm
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es-hot,es-warm
      - discovery.seed_hosts=es-hot
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es_warm_data:/usr/share/elasticsearch/data:Z
    networks:
      - elk
    depends_on:
      - es-hot

  logstash:
    image: logstash:7.17.2
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5044:5044
      - 5046:5046
    networks:
      - elk
    depends_on:
      - es-hot
      - es-warm

  kibana:
    image: kibana:7.17.2
    container_name: kibana
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - es-hot
      - es-warm

  filebeat:
    image: elastic/filebeat:7.17.2
    container_name: filebeat
    privileged: true
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
    command:
      - "-e"
      - "--strict.perms=false"
    networks:
      - elk
    depends_on:
      - logstash

  some_application:
    image: library/python:3.9-alpine
    container_name: some_app
    volumes:
      - ./pinger/run.py:/opt/run.py:Z
    entrypoint: python3 /opt/run.py
    depends_on:
      - logstash

  json_sender:
    image: curlimages/curl
    container_name: json_sender
    #command: ["sh","-c","while true; do curl -X POST -H \"Content-Type: application/json\" -d '{\"message\":\"Hello!\"}' 'logstash:5046' -m 1 ; sleep 4 ; done"]
    command: ["sh","-c","while true; do echo -n '{\"message\":\"Hello world!\"}' | nc -w1 logstash 5046 ; sleep 1 ; done"]
    networks:
      - elk
    depends_on:
      - logstash
