# Vault StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  labels:
    app: vault
spec:
  serviceName: vault
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault:1.12.1
        imagePullPolicy: IfNotPresent
        # Couldn't start vault with IPC_LOCK. Disabling IPC_LOCK, please use --cap-add IPC_LOCK
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        ports:
        - name: vault
          containerPort: 8200
          protocol: TCP
        # Resource Limits
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
        # Data Volume
        volumeMounts:
        - name: pvc
          mountPath: /vault/data
        # Environment variables
        args: ["server"]
        env:
        - name: VAULT_LOCAL_CONFIG
          value: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
            }
            storage "file" {
              path = "/vault/data"
            }
            log_level = "debug"
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: pvc-vault
---
# vault service
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  selector:
    app: vault
  type: ClusterIP
  ports:
  - name: vault
    protocol: TCP
    port: 8200
    targetPort: 8200
